### ISSUE TITLE
Image paste

### ISSUE THREAD

**Issue by AverTry** [TobiasTao/vscode-md#10]
Not sure if it's an issue, I'm trying to paste an image, or upload from local server,
Does your Extension support this? 
I have tried using Markdown Paste which works when your extension is not enabled, but it cannot paste through the wysiwyg or in the split editor.
I don't have outside picture accounts, and I'm using the windows version of vscode on win10 all updated.

Thanks for any help you can give.

**Comment by TobiasTao** [comment]
1. You can drag and drop a image:
- set:
![image](https://user-images.githubusercontent.com/37654563/96008640-5a5c6f80-0e72-11eb-90e4-38ead22be603.png)

- drag and drop a image:
![dropimage](https://user-images.githubusercontent.com/37654563/96008987-b32c0800-0e72-11eb-884a-4ec76040c551.gif)
!!notice: `vscode-md.image.dirPath` must Point to one of your vscode workspace folders (limited by vscode api)
i found a bug when `vscode-md.image.pathType`=absolute, i will fix it later.

2. upload a image to remote server:
https://github.com/TobiasTao/vscode-md/blob/master/docs/Upload-Image.md

**Comment by AverTry** [comment]
Thanks!

**Comment by TobiasTao** [comment]
move to #11
