### ISSUE TITLE
Custom theme background color and outline background color

### ISSUE THREAD

**Issue by hxse** [TobiasTao/vscode-md#23]
设置 Global theme 为 classic 大纲的背景色跟主题背景色同步了, 但是编辑器背景色是一片白色, 希望编辑器背景色也能跟主题背景色同步
最好可以自定义配色

**Comment by TobiasTao** [comment]
![image](https://user-images.githubusercontent.com/37654563/106359281-a7465200-634c-11eb-9617-65317555bb80.png)
你需要配置三种theme

**Comment by hxse** [comment]
选项太少了, 没办法自定义啊, classic选项会把正文背景色变成白色, 改不回来
我想要米黄背景色 ...
