### ISSUE TITLE
Space Waste from tab to toolbar

### ISSUE THREAD

**Issue by hxse** [TobiasTao/vscode-md#24]
标签页到编辑器工具栏之间的空白有点太大了

**Comment by TobiasTao** [comment]
![image](https://user-images.githubusercontent.com/37654563/106360189-170b0b80-6352-11eb-9c0a-1da6f1753447.png)
这个空间是给tooltip留的

**Comment by hxse** [comment]
@TobiasTao 有没有什么方法能把这个空间消除掉, 可以不要这个tooltip
