### ISSUE TITLE
automatic save image to ./assert path from drag imgae

### ISSUE THREAD

**Issue by hxse** [TobiasTao/vscode-md#25]
拖拽图片到编辑器会默认保存到当前路径, 但是怎么自动保存到当前路径下的 assert 文件夹, 研究半天没研究明白

**Comment by TobiasTao** [comment]
![image](https://user-images.githubusercontent.com/37654563/106359336-20de4000-634d-11eb-9239-022db8328ab2.png)
你需要配置这两个，可以参考本项目的配置：
![image](https://user-images.githubusercontent.com/37654563/106359348-38b5c400-634d-11eb-8482-c667a77659cf.png)
