### ISSUE TITLE
How to specify the markdown file default editor?

### ISSUE THREAD

**Issue by ziqiangxu** [TobiasTao/vscode-md#37]
I am not used to the `Markdown Edit` provided by this plugin `vscode all markdown`. 

If I want to use the built in Editor which is called `Text Editor`, I must right click the title of this file which is under editing, and select `Reopen Editor with ...` to switch to `Text Editor`.
![图片](https://user-images.githubusercontent.com/18530271/115953341-745fc480-a51d-11eb-85f7-491893082b40.png)

So if any way can I config the `Text Editor` which is built in as the default editor?
![图片](https://user-images.githubusercontent.com/18530271/115953134-3615d580-a51c-11eb-95b8-b86e36b91610.png)

**Comment by TobiasTao** [comment]
![image](https://user-images.githubusercontent.com/37654563/116075009-07872e80-a6c5-11eb-9343-c3b011118275.png)
Click the icon
