### ISSUE TITLE
No editors associated with document: XXX.md / Failed to save XXX.md:

### ISSUE THREAD

**Issue by TobiasTao** [TobiasTao/vscode-md#5]
stackoverflow: https://stackoverflow.com/questions/62065521/vscode-custom-edtior-extension-development-no-editors-associated-with-document

Failed to save XXX.md:
![image](https://user-images.githubusercontent.com/37654563/83503881-5dc01180-a4f6-11ea-9515-3f7305cc002f.png)

**Comment by TobiasTao** [comment]
The  `No editors associated with document: XXX.md`  warning was caused by extension: bracket-pair-colorizer.
But error `Failed to save XXX.md` still exist:
when white dot appeared:
![image](https://user-images.githubusercontent.com/37654563/83944121-adbf1100-a833-11ea-8f85-9d4d69d85fff.png)
then press `ctrl + s` to save all, error occur:
![image](https://user-images.githubusercontent.com/37654563/83944119-a3047c00-a833-11ea-95cc-3763cbf7c8b6.png)

**Comment by jakekwak** [comment]
No error in my macbook pro. How can I test this issue.

**Comment by TobiasTao** [comment]
I dont know when this white dot will appear, it seems to be irregular

**Comment by jakekwak** [comment]
try to clean install to other computer.   I will  test this my windows computer tomorrow.

**Comment by jakekwak** [comment]
It is OK even on Windows. but it is automatically saved(I didn't turn on autosave option)
![vditor69](https://user-images.githubusercontent.com/15811943/83970656-7173cb00-a89c-11ea-980d-079b3a3eb616.gif)

**Comment by TobiasTao** [comment]
Thanks for your test @jakekwak 
vscode-md will automatically save markdown file：
https://github.com/TobiasTao/vscode-md/blob/master/media/main.js#L75
