### ISSUE TITLE
Create a separate extension dedicated to image drag-and-drop?

### ISSUE THREAD

**Issue by iaeiou** [TobiasTao/vscode-md#50]
Hi there,

the drag-and-drop feature provided by this extension is promising!

I can't get it to work and I'm afraid too much features are concentrated here.  
I just want to drag and drop pictures!

Do you consider shipping this feature in a separate extension?
Thanks!

**Comment by TobiasTao** [comment]
recommended：https://marketplace.visualstudio.com/items?itemName=mushan.vscode-paste-image

**Comment by iaeiou** [comment]
Thanks, `Paste Image` requires to paste **from the clipboard**, I hoped another extension could have achieved drag-and-drop.

I'm testing now "[Auto Import](https://github.com/ElecTreeFrying/auto-import-relative-path/blob/master/DEMO.md#markdown-support) Image to Markdown" and we are close to perfection!

Anyway, thanks!
