### ISSUE TITLE
[Question] How to activate vscode-md extension

### ISSUE THREAD

**Issue by jakekwak** [TobiasTao/vscode-md#6]
Please let me know how to setup(install) this vscode-md.

**Comment by TobiasTao** [comment]
Hi @jakekwak , I’m not going to publish it to the app market until #5  is resolved。
If you want to try it：
```
// 1. clone project

// 2.
npm install
//3
vsce package
// 4
code --install-extension vscode-md-0.2.0.vsix
```

**Comment by jakekwak** [comment]
Thanks
