### ISSUE TITLE
Not Working??

### ISSUE THREAD

**Issue by sebi5361** [TobiasTao/vscode-md#9]
I have installed *vscode-md* but something must be wrong because I cannot see its toolbar with *Toggle Edit Mode*!?
I have access to *vscode-md* settings under the general settings, thus it must be installed correctly, but still it isn't working as in the demo animated picture.
Could you help me solve that issue?

**Comment by TobiasTao** [comment]
make sure this option is not turned on:
![image](https://user-images.githubusercontent.com/37654563/95668512-8d1f1300-0ba7-11eb-948a-e2faf9c076fe.png)

Please give me a screenshot after opening the markdown file like this:
![image](https://user-images.githubusercontent.com/37654563/95668563-54cc0480-0ba8-11eb-8c6b-6472c6d0122a.png)

**Comment by sebi5361** [comment]
I have checked an I didn't have that option turned on...

I have just noticed that it does work indeed! ...on a basic file... Thus I get a similar screenshoot than yours.
![image](https://user-images.githubusercontent.com/18078043/95669711-c6458c00-0b83-11eb-8122-019b4f981505.png)

However it doesn't work with the file I tried first:
![image](https://user-images.githubusercontent.com/18078043/95669734-f2f9a380-0b83-11eb-8a4c-8687572f6612.png)

I have just understood that this has to do with the file name:
**The filename to be rendered properly shouldn't contain any whitespace.**
Thus it works with a similar file with a simpler name:
![image](https://user-images.githubusercontent.com/18078043/95669783-8af78d00-0b84-11eb-9ad4-685728150f29.png)

However, there is a different issue:
**AsciiMath is not rendered properly**
...for both inline and display equations.

**Comment by TobiasTao** [comment]
1, filename can contain whitespaces:
![image](https://user-images.githubusercontent.com/37654563/95670236-358aa280-0bbb-11eb-8017-79aaa09259e5.png)
2. vscode-md does not support AsciiMath, its mathematical formula rendering engine is [Katex](https://katex.org/ ): 
![image](https://user-images.githubusercontent.com/37654563/95670309-0294de80-0bbc-11eb-810b-9dbe3ce73f82.png)

**Comment by sebi5361** [comment]
> 1. filename can contain whitespaces:

Even such as this: ***Heat Transfer Formulas AM.md***? (my original faulty file)
 
> 2. vscode-md does not support AsciiMath, its mathematical formula rendering engine is [Katex](https://katex.org/):

Indeed. Sorry for that. I was mixing  things up...

**Comment by TobiasTao** [comment]
it still works fine with `Heat Transfer Formulas AM.md`:
![image](https://user-images.githubusercontent.com/37654563/95679375-f3864e80-0c04-11eb-951b-c99af2e7c8b6.png)
